services:
  db_drivenOps:
    image: postgres
    container_name: db_drivenOps
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env
    volumes:
      - pg_drivenOps:/var/lib/postgresql/data

  node_app_driven_ops:
    container_name: driven_ops
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_drivenOps
    env_file:
      - .env

volumes:
  pg_drivenOps: